### ISSUE TITLE
How to remove templates?

### ISSUE THREAD

**Issue by samwalls** [oliyh/slacky#25]
Someone on my team has uploaded two templates of the same name, and now there are literally two in the list with the same keyword. Is there any way to remove templates?

**Comment by oliyh** [comment]
Hi @samdeman22 
There is no way currently, although I would like to build a UI for managing this sort of thing. For now, can you let me know your team name and I will remove the duplicated entries, and I'll probably add a constraint to prevent this in future.

Thanks

**Comment by oliyh** [comment]
See #27
