### ISSUE TITLE
Duplicate templates

### ISSUE THREAD

**Issue by queesamor** [oliyh/slacky#28]
It appears that if a template is created multiple times with the same name, it will register as multiple templates, and when referencing the template for future use, only the first version will be used.

**Comment by oliyh** [comment]
Hi @queesamor,

Thanks for the report. I think this is a duplicate of #25. Would you expect the later version to overwrite the first?

Thanks

**Comment by oliyh** [comment]
Closing as can be resolved using `:delete-template` as per #27
