### ISSUE TITLE
Find alternative to memecaptain

### ISSUE THREAD

**Issue by oliyh** [oliyh/slacky#31]
Memecaptain is gone for good, due to cost of running it.

One alternative is to generate them locally but non-persistently, and indicate to users that they have a limited amount of time to save it for their own use

**Comment by oliyh** [comment]
Limited functionality is restored. Templates cannot currently be created or used.

**Comment by oliyh** [comment]
Templates can be used again

**Comment by oliyh** [comment]
Still to do:
- Clean up generated memes after some threshold
- Store input files longer, have a cleanup threshold here too
- Delete dead memecaptain code and tests
- Some image urls don't work so well, e.g. missing file extensions, dodgy https

**Comment by radfahrer** [comment]
https://api.imgflip.com/

**Comment by oliyh** [comment]
Hi @radfahrer

Thanks for the suggestion. imgflip's API doesn't let you create templates so is unsuitable for Slacky. The current deployment is working again using a local memecaptain instance so I will be closing this issue once I've worked out the last few issues above.

Cheers
